labels:
  0: 'noise'
  1: 'animal'
  2: 'human.pedestrian.adult'
  3: 'human.pedestrian.child'
  4: 'human.pedestrian.construction_worker'
  5: 'human.pedestrian.personal_mobility'
  6: 'human.pedestrian.police_officer'
  7: 'human.pedestrian.stroller'
  8: 'human.pedestrian.wheelchair'
  9: 'movable_object.barrier'
  10: 'movable_object.debris'
  11: 'movable_object.pushable_pullable'
  12: 'movable_object.trafficcone'
  13: 'static_object.bicycle_rack'
  14: 'vehicle.bicycle'
  15: 'vehicle.bus.bendy'
  16: 'vehicle.bus.rigid'
  17: 'vehicle.car'
  18: 'vehicle.construction'
  19: 'vehicle.emergency.ambulance'
  20: 'vehicle.emergency.police'
  21: 'vehicle.motorcycle'
  22: 'vehicle.trailer'
  23: 'vehicle.truck'
  24: 'flat.driveable_surface'
  25: 'flat.other'
  26: 'flat.sidewalk'
  27: 'flat.terrain'
  28: 'static.manmade'
  29: 'static.other'
  30: 'static.vegetation'
  31: 'vehicle.ego'
labels_16:
  0: 'noise'
  1: 'barrier'
  2: 'bicycle'
  3: 'bus'
  4: 'car'
  5: 'construction_vehicle'
  6: 'motorcycle'
  7: 'pedestrian'
  8: 'traffic_cone'
  9: 'trailer'
  10: 'truck'
  11: 'driveable_surface'
  12: 'other_flat'
  13: 'sidewalk'
  14: 'terrain'
  15: 'manmade'
  16: 'vegetation'
learning_map:
  1: 0
  5: 0
  7: 0
  8: 0
  10: 0
  11: 0
  13: 0
  19: 0
  20: 0
  0: 0
  29: 0
  31: 0
  9: 1
  14: 2
  15: 3
  16: 3
  17: 4
  18: 5
  21: 6
  2: 7
  3: 7
  4: 7
  6: 7
  12: 8
  22: 9
  23: 10
  24: 11
  25: 12
  26: 13
  27: 14
  28: 15
  30: 16

color_map: # bgr
  0: [0, 0, 0]
  1: [0, 0, 0]
  2: [0, 0, 230]
  3: [0, 0, 230]
  4: [0, 0, 230]
  5: [0, 0, 0]
  6: [0, 0, 230]
  7: [0, 0, 0]
  8: [0, 0, 0]
  9: [112, 128, 144]
  10: [0, 0, 0]
  11: [0, 0, 0]
  12: [47, 79, 79]
  13: [0, 0, 0]
  14: [220, 20, 60]
  15: [255, 127, 80]
  16: [255, 127, 80]
  17: [255, 158, 0]
  18: [233, 150, 70]
  19: [0, 0, 0]
  20: [0, 0, 0]
  21: [255, 61, 99]
  22: [255, 140, 0]
  23: [255, 99, 71]
  24: [0, 207, 191]
  25: [175, 0, 75]
  26: [75, 0, 75]
  27: [112, 180, 60]
  28: [222, 184, 135]
  29: [0, 0, 0]
  30: [0, 175, 0]
  31: [0, 0, 0]

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "fence"
  15: False    # "vegetation"
  16: False    # "trunk"